### ISSUE TITLE
pdo driver unable to update value used in where clause

### ISSUE THREAD

**Issue by breman** [webreactor/reactor4-dev#20]
https://github.com/webreactor/reactor4-dev/blob/dev-max/Reactor/Database/PDO/Connection.php#L126

since we cant use variable links twice theres an issue that we cant update data value that was used in where clause, like this:
```UPDATE tbl SET a=1 WHERE a=0;```

`array_merge` will take just last one, but anyway we have an error of using variable link twice like this:
```UPDATE tbl SET a=:a WHERE a=:a;```

ofc we can use static `$where`, but theres more native way is to make some different prefixes to where and set clauses, like this:
```UPDATE tbl SET a=:set_a WHERE a=:where_a;```

**Comment by toecto** [comment]
Solved
https://github.com/webreactor/reactor4-dev/commit/a7ac413d762997883ead9659de001b2175a75bea
